save_directory: "/home/ash/sheffield_experiments_02_Apr_2025/" # this is where the map is saved
scan_topic: "/okdo/scan"  
bag_root_folder: "/home/ash/sheffield_experiments_02_Apr_2025/"  # This folder has several .db3 files
